Kuzzle:
  scale: 1
Redis:
  scale: 1
Elasticsearch:
  scale: 1
KuzzleBo:
  scale: 1

.catalog:
  name: "Kuzzle failover"
  version: "v1.0.0"
  description: "Kuzzle"
  questions:
    - variable: "http_port"
      description: "HTTP port"
      label: "HTTP port"
      required: true
      default: "7511"
      type: "int"
    - variable: "ws_port"
      description: "Websocket port"
      label: "Websocket port"
      required: true
      default: "7512"
      type: "int"
    - variable: "bo_http_port"
      description: "Back Office HTTP port"
      label: "HTTP port"
      required: true
      default: "3000"
      type: "int"
    - variable: "kibana_port"
      description: "Kibana HTTP port"
      label: "Kibana HTTP port"
      required: true
      default: "3000"
      type: "int"